import mongoose,{Schema} from "mongoose";

const chargerSchema = new Schema({
    CableName:{
        type:String,
        require:true,
        trim:true,
    },
    MRP_Price:{
        type:Number,
    },
    Discount_Price:{
        type:Number,
    },
    Oringinal_Price:{
        type:Number,
    },
    Cable_Image:[
        {
            type:String,
            require:true,
        }
    ],
    Cable_Highlight:{
        Cable_Length:{
            type:String,
            require:true,
            trim:true,
        },
        charger_Type:{
            type:String,
            require:true,
            trim:true,
        },
        Cable_Connector:{
            type:String,
        },
        Cable_Speed:{
            type:String,
        },
        Cable_device:{
            type:String,
        },
    },
    Product_Description:[
        {
          Specication:{
            type:String,
            require:true,
          },
           Detail_Description:{
            type:String,
            require:true,
          },
          Description_Image:{
            type:String,
          }
        }
    ],
    Specification:{
        In_The_Box:{
            type:String,
        },
        General:{
            Brand_Name:{
                type:String,
            },
            Cable_Type:{
                type:String,
            },
            Cable_Speed:{
                type:String,
            },
            Connector_1:{
                type:String,
            },
            Connector_2:{
                type:String,
            },
            Cable_Shape:{
                type:String,
            },
            Part_Number:{
                type:String,
            },
            Cable_Model:{
                type:String,
            },
            Compatible_Devices:{
                type:String,
            },
            Color:{
                type:String,
            },
            Suitable_For:[{type:String}],
            Cable_Length:{
                type:String,
            },
            Net_Quantity:{
                type:Number,
            },
            Cable_Material:{
                type:String,
            },
            Support_3D_Video:{
                type:String,
            },
             Maximum_Current_Transmission:{
                type:String,
             }
        },
        Warranty:{
                Warranty_Summary:{
                    type:String,
                },
                Covered_in_Warranty:{
                    type:String,
                },
                Not_Covered_in_Warranty:{
                    type:String,
                },
                Warranty_Service_Type:{
                    type:String,
                },
        },
    },
})